import os
import pandas as pd

configfile: "config/config.yaml"
samples = pd.read_csv(config["samples"],index_col="sample",sep="\t")

# Flags to enable/disable steps of the workflow
ENABLE_SHORT_READS = config.get("short_reads", {}).get("enabled", True)
ENABLE_RESISTANCE_SCREENING = config.get("resistance_screening", {}).get("enabled", True)
ENABLE_PROTEIN_ANALYSIS = config.get("protein_analysis", {}).get("enabled", True)

include: "rules/helper_functions.smk"

include: "rules/01_read_qc.smk"
include: "rules/02_assembly.smk"
include: "rules/03_polishing.smk"
include: "rules/04_assembly_qc.smk"
include: "rules/05_annotation.smk"
include: "rules/06_resistance_genes.smk"
include: "rules/07_comparative_genomics.smk"
include: "rules/08_protein_analysis.smk"

all_targets = [
    "results/qc/multiqc_long/multiqc_report.html",
    "results/qc/multiqc_assembly/multiqc_assembly_report.html",
    "results/comparative/final_species_tree.tre"
    ]
    
if ENABLE_SHORT_READS:
  all_targets.append("results/qc/multiqc_short/multiqc_report.html")
if ENABLE_RESISTANCE_SCREENING:
  all_targets.extend(["results/qc/multiqc_resistance/multiqc_report.html", "results/resistance_screening/all_samples.tsv"])
if ENABLE_PROTEIN_ANALYSIS:
  all_targets.append("results/protein_analysis/phylogenetic_tree_plot.png")

rule all:
  input:
    all_targets
