import os
import pandas as pd

configfile: "config/config.yaml"
samples = pd.read_csv(config["samples"],index_col="sample",sep="\t")

include: "rules/01_read_qc.smk"
include: "rules/02_assembly.smk"
include: "rules/03_polishing.smk"
include: "rules/04_assembly_qc.smk"
include: "rules/05_annotation.smk"
include: "rules/06_resistance_genes.smk"
include: "rules/07_comparative_genomics.smk"
include: "rules/08_protein_analysis.smk"

rule all:
  input:
    "results/qc/multiqc/multiqc_report.html"
