samples : "config/samples_set2_ont.tsv"

# --------------------------------------------------------------------
# enable/disable steps of the workflow

short_reads:
  enabled: true

resistance_screening:
  enabled: true

protein_analysis:
  enabled: true

# --------------------------------------------------------------------
# 01_read_qc

multiqc:
  extra: ""

multiqc_assembly:
  extra: "--dirs" # to look at parents for busco

sequali:
  extra: ""

fastplong:
  extra: "--length_required 1000"

fastqc:
  extra: "--quiet"

fastp:
  extra: "--length_required 36 --cut_front --cut_tail --cut_mean_quality 15"

# --------------------------------------------------------------------
# 02_assembly

flye:
  params:
    PacBio: "--pacbio-raw"
    MinION: "--nano-hq"
    default: "--nano-raw"

# --------------------------------------------------------------------
# 03_polishing

minimap2_long:
  params:
    PacBio: "map-pb"
    MinION: "map-ont"
    default: "map-ont"

pilon:
  params:
    java_mem: "16G"
# --------------------------------------------------------------------
# 04_assembly_qc

# --------------------------------------------------------------------
# 05_annotation

bakta:
  db_path: "resources/db_bakta"
  db_type: "light"  #change as wanted between 'full' or 'light'

# --------------------------------------------------------------------
# 06_resistance_genes

screening:
  extra: ""

card:
  db_path: "resources/db_card"
# --------------------------------------------------------------------
# 07_comparative_genomics

comparative_genomics:
  external_genome : ""
  core_threshold: 0.95 #1.00 is too strict
  
# --------------------------------------------------------------------
# 08_protein_analysis

protein_set:
  path: "resources/protein_set.faa"

blastp:
  extra: ""
  max_target_seqs: 10

msa:
  extra: ""

phylogenetic_tree:
  extra: ""