ref : "/data/reference.fa"
samples : "config/samples.tsv"

#Trimmomatic parameters
trimmomatic:
  adapters: "resources/adapters/TruSeq3-PE-2.fa"
  illuminaclip: "2:30:10"
  extra: "LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"