samples : "config/samples_set1.tsv"

# --------------------------------------------------------------------
# configuration for the workflow

short_reads:
  enabled: true

# --------------------------------------------------------------------
# 01_read_qc

multiqc:
  extra: ""

multiqc_assembly:
  extra: "--dirs" # to look at parents for busco

sequali:
  extra: ""

fastplong:
  extra: "--length_required 1000"

fastqc:
  extra: "--quiet"

fastp:
  extra: "--length_required 36 --cut_front --cut_tail --cut_mean_quality 15"

# --------------------------------------------------------------------
# 02_assembly

flye:
  params:
    PacBio: "--pacbio-raw"
    MinION: "--nano-hq"
    default: "--nano-raw"

# --------------------------------------------------------------------
# 03_polishing

minimap2_long:
  params:
    PacBio: "map-pb"
    MinION: "map-ont"
    default: "map-ont"

pilon:
  params:
    java_mem: "16G"
# --------------------------------------------------------------------
# 04_assembly_qc

# --------------------------------------------------------------------
# 05_annotation

# --------------------------------------------------------------------
# 06_resistance_genes

# --------------------------------------------------------------------
# 07_comparative_genomics

# --------------------------------------------------------------------
# 08_protein_analysis
